version: '3.7'

networks:
  default:
    external:
      name: sagemaker-local

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    container_name: minio
    command: gateway azure
    restart: unless-stopped
    environment:
      - MINIO_ACCESS_KEY=${LOCAL_ACCESS_KEY_ID}
      - MINIO_SECRET_KEY=${LOCAL_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${LOCAL_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${LOCAL_SECRET_ACCESS_KEY}
  minio-log:
    image: minio/minio
    ports:
      - "9001:9001"
    container_name: minio-log
    command: server --address :9001 /data
    volumes:
      - /mnt/deepracer/robo/checkpoint:/data
    restart: unless-stopped
    environment:
      - MINIO_ACCESS_KEY=${LOCAL_ACCESS_KEY_ID}
      - MINIO_SECRET_KEY=${LOCAL_SECRET_ACCESS_KEY}
  rl_coach:
    image: aschu/rl_coach
    environment:
      - WORLD_NAME
      - PRETRAINED
      - PRETRAINED_S3_PREFIX
      - PRETRAINED_S3_BUCKET
      - MODEL_S3_PREFIX=${LOCAL_S3_MODEL_PREFIX}
      - MODEL_S3_BUCKET=${LOCAL_S3_BUCKET}
      - S3_ENDPOINT_URL=${LOCAL_S3_ENDPOINT_URL}
      - MODEL_METADATA_FILE_S3_KEY=${LOCAL_S3_CUSTOM_FILES_PREFIX}/model_metadata.json
      - REWARD_FILE_S3_KEY=${LOCAL_S3_CUSTOM_FILES_PREFIX}/reward.py
      - METRICS_S3_BUCKET=${LOCAL_S3_BUCKET}
      - HYPERPARAMETER_FILE_S3_KEY=${LOCAL_S3_CUSTOM_FILES_PREFIX}/hyperparameters.json
      - SAGEMAKER_SHARED_S3_PREFIX=${LOCAL_S3_MODEL_PREFIX}
      - SAGEMAKER_SHARED_S3_BUCKET=${LOCAL_S3_BUCKET}
      - AWS_ACCESS_KEY_ID=${LOCAL_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${LOCAL_SECRET_ACCESS_KEY}
    env_file: .env
    container_name: rl_coach
    volumes:
    - '//var/run/docker.sock:/var/run/docker.sock'
    - '../deepracer/sagemaker-python-sdk:/deepracer/sagemaker-python-sdk'
    - '../deepracer/rl_coach:/deepracer/rl_coach'
    - '/robo/container:/robo/container'
    depends_on:
    - minio
  robomaker:
    image: larsll/deepracer_robomaker:latest
    command: ["${ROBOMAKER_COMMAND}"]
    volumes:
      - ../deepracer/simulation/aws-robomaker-sample-application-deepracer/simulation_ws/src:/app/robomaker-deepracer/simulation_ws/src
      - /mnt/deepracer/robo/checkpoint:/root/.ros/
      - /mnt/deepracer/recording:/mnt/recording
    ports:
      - "8080:5900"
    container_name: robomaker
    restart: unless-stopped
    environment:
      - CHANGE_START_POSITION
      - WORLD_NAME
      - MODEL_S3_PREFIX=${LOCAL_S3_MODEL_PREFIX}
      - MODEL_S3_BUCKET=${LOCAL_S3_BUCKET}
      - S3_ENDPOINT_URL=${LOCAL_S3_ENDPOINT_URL}
      - MODEL_METADATA_FILE_S3_KEY=${LOCAL_S3_CUSTOM_FILES_PREFIX}/model_metadata.json
      - REWARD_FILE_S3_KEY=${LOCAL_S3_CUSTOM_FILES_PREFIX}/reward.py
      - METRICS_S3_BUCKET=${LOCAL_S3_BUCKET}
      - HYPERPARAMETER_FILE_S3_KEY=${LOCAL_S3_CUSTOM_FILES_PREFIX}/hyperparameters.json
      - SAGEMAKER_SHARED_S3_PREFIX=${LOCAL_S3_MODEL_PREFIX}
      - SAGEMAKER_SHARED_S3_BUCKET=${LOCAL_S3_BUCKET}
      - AWS_ACCESS_KEY_ID=${LOCAL_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${LOCAL_SECRET_ACCESS_KEY}
    env_file: .env
    depends_on:
    - rl_coach
